from_latest_tag = false
branch_whitelist = ["main"]
pre_bump_hooks = [
    "hatch version {{version}}"
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]

[changelog]
path = "CHANGELOG.md"
authors = [
    { signature = "Marc Ende", username = "eBeyond" },
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
# stop the build if there are Python syntax errors or undefined names
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
# exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
flake8 . --count --exit-zero --statistics
"""

# Or file path
[git_hooks.pre-push]
path = "hooks/pre-push.sh"

