# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch build flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Semver release
      id: release
      uses: cocogitto/cocogitto-action@v3.5
      with:
        release: true
        git-user: 'github-actions'
        git-user-email: 'github-actions@github.com'

    - name: Generate Changelog
      run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

    - name: Build package
      run: python -m build

    - name: Upload github release
      uses: softprops/action-gh-release@v1
      with:
        body_path: GITHUB_CHANGELOG.md
        tag_name: ${{ steps.release.outputs.version }}

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.whl"
        omitBody: true
        prerelease: true
        tag: ${{ steps.release.outputs.version }}